### ISSUE TITLE
Lambyでパラメータストアから環境変数を参照できない

### ISSUE THREAD

**Issue by kanade0525** [kanade0525/esoteric_words#18]
```yaml
# template.yaml

Globals:
  Function:
    Environment:
      Variables:
        MYSQL_HOST: x-crypteia-ssm:/myapp/MYSQL_HOST
        MYSQL_ADMIN_USER: x-crypteia-ssm:/myapp/MYSQL_ADMIN_USER
        MYSQL_ADMIN_PASSWORD: x-crypteia-ssm:/myapp/MYSQL_ADMIN_PASSWORD
```
と設定すると以下のように出てしまった。
https://lamby.cloud/docs/environment

```bash
{
    "All": "all",
    "ErrorMessage": "Error calling ssm:GetParameter. Environment variable: MYSQL_ADMIN_PASSWORD Path: x-crypteia-ssm:/esoteric/MYSQL_ADMIN_PASSWORD Error: dispatch failure",
    "_aws": {
        "CloudWatchMetrics": [
            {
                "Dimensions": [
                    [
                        "All",
                        "ssm"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "error",
                        "Unit": "Count"
                    }
                ],
                "Namespace": "Crypteia"
            }
        ],
        "Timestamp": 1745744741735
    },
    "error": 1,
    "ssm": "ssm"
}
```

**Comment by kanade0525** [comment]
下記のように設定することで無事解消

```yaml
# template.yaml

Globals:
  Function:
    Environment:
      Variables:
        MYSQL_HOST: !Sub '{{resolve:ssm:/esoteric/MYSQL_HOST}}'
        MYSQL_ADMIN_USER: !Sub '{{resolve:ssm:/esoteric/MYSQL_ADMIN_USER}}'
        MYSQL_ADMIN_PASSWORD: !Sub '{{resolve:ssm:/esoteric/MYSQL_ADMIN_PASSWORD}}'
```
